# Generated by Django 4.1.3 on 2022-11-16 13:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_skill_status_skill_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
