# Generated by Django 4.1.3 on 2023-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_language_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Bio',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='university',
            new_name='university_name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='rating',
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.CharField(default='Aadil', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('PROFESSIONAL_SKILL', 'Professional Skill'), ('SOFTWARE_SKILL', 'Software Skill')], default='SOFTWARE_SKILL', max_length=18),
        ),
    ]
